/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
//  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
 /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
 */
 tutorialSidebar: [
  {
    type: 'category',
    label: 'MentorED Platform Documentation',
    items: [

          {
            type: 'category',
            label: 'Getting Started with MentorED',
            items: [
              {
                type: 'doc',
                id: 'intro', // document ID
                label: 'Introduction', // sidebar label
              },
              {
                type: 'category',
                label: 'Key MentorED Components',
                items: [
                  {
                    type: 'doc',
                    id: 'technicalarchitecture-mentored', // document ID
                    label: 'Architecture', // sidebar label
                  },
                  {
                      type: 'category',
                      label: 'Microservices',
                      items: [
                      {
                          type: 'doc',
                          id: 'settingup-userservice', // document ID
                          label: 'Setting up the User Service', // sidebar label
                      },
                      {
                          type: 'doc',
                          id: 'settingup-mentoringservice', // document ID
                          label: 'Setting up the Mentoring Service', // sidebar label
                      },
                      {
                          type: 'doc',
                          id: 'settingup-notificationsservice', // document ID
                          label: 'Setting up the Notifications Service', // sidebar label
                      },
                    ]
                  },
                ]
              },
            {
              type: 'category',
              label: 'Key Capabilities of MentorED',
              items: [
                {
                  type: 'doc',
                  id: 'key-capabilities', // document ID
                  label: 'User and Role Management', // sidebar label
                },
                {
                  type: 'doc',
                  id: 'key-capabilities', // document ID
                  label: 'Schedule Mentoring Sessions', // sidebar label
                },
                {
                  type: 'doc',
                  id: 'key-capabilities', // document ID
                  label: 'Promote Sessions', // sidebar label
                },
                {
                  type: 'doc',
                  id: 'key-capabilities', // document ID
                  label: 'Discover Mentors', // sidebar label
                },
                {
                  type: 'doc',
                  id: 'key-capabilities', // document ID
                  label: 'Discover Sessions', // sidebar label
                },
                {
                  type: 'doc',
                  id: 'key-capabilities', // document ID
                  label: 'Conduct Live Mentoring Sessions', // sidebar label
                },
                {
                  type: 'doc',
                  id: 'key-capabilities', // document ID
                  label: 'Record and Share Sessions', // sidebar label
                },
                {
                  type: 'doc',
                  id: 'key-capabilities', // document ID
                  label: 'Analyze Feedback on Sessions', // sidebar label
                }
              ]
            },
          ]
        },

        {
          type: 'category',
          label: 'MentorED Mobile Application',
          items: [
            {
              type: 'doc',
              id: 'using-the-mentored-mobile-application', // document ID
              label: 'About the MentorED Mobile Application', // sidebar label
            },
            {
              type: 'doc',
              id: 'overview', // document ID
              label: 'Overview', // sidebar label
            },
 
        
            {
              type: 'category',
              label: 'MentorED for Mentors',
              items: [
                  {
                    type: 'doc',
                    id: 'mentored-mobile-application-for-mentors', // document ID
                    label: 'MentorED for Mentors', // sidebar label
                  },
                  {
                    type: 'doc',
                    id: 'signing-up-as-a-mentor', // document ID
                    label: 'Signing up as a Mentor', // sidebar label
                  },
                  {
                    type: 'doc',
                    id: 'creating-and-managing-mentor-profile', // document ID
                    label: 'Creating a Mentor Profile', // sidebar label
                  },
                  {
                    type: 'doc',
                    id: 'mentor-directory', // document ID
                    label: 'Using the Mentor Directory', // sidebar label
                  },
                  {
                    type: 'doc',
                    id: 'setting-up-a-mentored-session', // document ID
                    label: 'Setting up a Mentored Session', // sidebar label
                  },
                  {
                    type: 'doc',
                    id: 'inviting-mentorsandmentees-host', // document ID
                    label: 'Inviting Mentors and Mentees', // sidebar label
                  },
                  {
                    type: 'doc',
                    id: 'starting-a-session', // document ID
                    label: 'Starting a Mentoring Session', // sidebar label
                  },
                  {
                    type: 'doc',
                    id: 'feedbackformentors', // document ID
                    label: 'Feedback for Mentors', // sidebar label
                  }
              ]
            },

            {
              type: 'category',
              label: 'MentorED for Mentees',
              items: [
                  {
                    type: 'doc',
                    id: 'mentored-mobile-application-for-mentees', // document ID
                    label: 'MentorED for Mentees', // sidebar label
                  },
                  {
                    type: 'doc',
                    id: 'signing-up-as-a-mentee', // document ID
                    label: 'Signing up as a Mentee', // sidebar label
                  },
                  {
                    type: 'doc',
                    id: 'creating-and-managing-mentee-profile', // document ID
                    label: 'Creating a Mentee Profile', // sidebar label
                  },
                  {
                    type: 'doc',
                    id: 'mentor-directory', // document ID
                    label: 'Using the Mentor Directory', // sidebar label
                  },
                  {
                    type: 'doc',
                    id: 'enrolling-for-a-session', // document ID
                    label: 'Enrolling for a Mentored Session', // sidebar label
                  },
                  {
                    type: 'doc',
                    id: 'inviting-mentorsandmentees-participants', // document ID
                    label: 'Inviting Mentors and Mentees', // sidebar label
                  },
                  {
                    type: 'doc',
                    id: 'joining-a-session', // document ID
                    label: 'Joining a Mentoring Session', // sidebar label
                  },
                  {
                    type: 'doc',
                    id: 'feedbackformentees', // document ID
                    label: 'Providing Feedback on a Session', // sidebar label
                  }
              ]
            },
          ]
        },
      ]
    }
  ]
};

module.exports = sidebars;
